create table if not exists public.task_lists (
  id uuid primary key default gen_random_uuid(),
  nome text not null check (length(trim(nome)) between 1 and 200),
  brand_id uuid not null references public.brands(id),
  campanha_id text,
  criado_por uuid references auth.users(id) default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  arquivado_em timestamptz,
  arquivado_por uuid references auth.users(id),
  unique (brand_id, nome)
);

create table if not exists public.legacy_member_links (
  legacy_name text primary key,
  profile_id uuid not null references public.profiles(id),
  migrado_por uuid references auth.users(id) default auth.uid(),
  migrado_em timestamptz not null default now(),
  tarefas_migradas integer not null default 0,
  check (length(trim(legacy_name)) > 0)
);

create table if not exists public.task_action_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) default auth.uid(),
  origin text not null check (origin in ('interface','mcp')),
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  actor_id uuid references auth.users(id) default auth.uid(),
  kind text not null,
  title text not null,
  body text,
  task_id text,
  event_key text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create unique index if not exists notifications_event_once_idx
  on public.notifications(user_id, kind, coalesce(task_id,''), coalesce(event_key,''))
  where event_key is not null;

alter table public.equipe_convites
  add column if not exists enviado_em timestamptz,
  add column if not exists aceito_em timestamptz;

alter table public.task_lists enable row level security;
alter table public.legacy_member_links enable row level security;
alter table public.task_action_audit enable row level security;
alter table public.notifications enable row level security;

drop policy if exists task_lists_read on public.task_lists;
create policy task_lists_read on public.task_lists for select to authenticated
using (app.estou_ativo() and not app.eh_externo());
drop policy if exists task_lists_insert on public.task_lists;
create policy task_lists_insert on public.task_lists for insert to authenticated
with check (app.estou_ativo() and not app.eh_externo());
drop policy if exists task_lists_update on public.task_lists;
create policy task_lists_update on public.task_lists for update to authenticated
using (app.estou_ativo() and not app.eh_externo())
with check (app.estou_ativo() and not app.eh_externo());

drop policy if exists legacy_member_links_read on public.legacy_member_links;
create policy legacy_member_links_read on public.legacy_member_links for select to authenticated
using (app.estou_ativo() and not app.eh_externo());
drop policy if exists legacy_member_links_admin on public.legacy_member_links;
create policy legacy_member_links_admin on public.legacy_member_links for all to authenticated
using (app.sou_admin()) with check (app.sou_admin());

drop policy if exists task_action_audit_read on public.task_action_audit;
create policy task_action_audit_read on public.task_action_audit for select to authenticated
using (app.estou_ativo() and not app.eh_externo());
drop policy if exists task_action_audit_insert on public.task_action_audit;
create policy task_action_audit_insert on public.task_action_audit for insert to authenticated
with check (app.estou_ativo() and not app.eh_externo() and actor_id=(select auth.uid()));

drop policy if exists notifications_read_own on public.notifications;
create policy notifications_read_own on public.notifications for select to authenticated
using (user_id=(select auth.uid()));
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications for update to authenticated
using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
drop policy if exists notifications_insert_internal on public.notifications;
create policy notifications_insert_internal on public.notifications for insert to authenticated
with check (
  app.estou_ativo() and not app.eh_externo()
  and actor_id=(select auth.uid())
  and exists(select 1 from public.profiles p where p.id=user_id and p.ativo)
);

grant select, insert, update on public.task_lists to authenticated;
grant select, insert, update on public.legacy_member_links to authenticated;
grant select, insert on public.task_action_audit to authenticated;
grant select, insert, update on public.notifications to authenticated;
grant usage, select on sequence public.task_action_audit_id_seq to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

drop trigger if exists task_lists_touch on public.task_lists;
create trigger task_lists_touch before update on public.task_lists
for each row execute function app.touch_atualizado_em();

insert into public.task_lists(nome, brand_id, campanha_id)
select distinct coalesce(nullif(trim(e->>'project'),''),'Operação'), b.id, nullif(e->>'campaignId','')
from public.operacional_estado o
cross join lateral jsonb_array_elements(o.valor) e
join public.brands b on lower(b.nome)=lower(coalesce(e->>'brand',''))
where o.chave='central.tasks.vitor-gutierrez' and o.dono is null
on conflict (brand_id,nome) do nothing;

update public.operacional_estado o
set valor=(
  select coalesce(jsonb_agg(
    case when tl.id is null then e else e || jsonb_build_object('listId',tl.id::text) end
    order by ord
  ),'[]'::jsonb)
  from jsonb_array_elements(o.valor) with ordinality a(e,ord)
  left join public.brands b on lower(b.nome)=lower(coalesce(e->>'brand',''))
  left join public.task_lists tl on tl.brand_id=b.id and tl.nome=coalesce(nullif(trim(e->>'project'),''),'Operação')
)
where o.chave in ('central.tasks.vitor-gutierrez','allianceos.tasks.vitor-gutierrez')
  and o.dono is null and jsonb_typeof(o.valor)='array';

create or replace function app.ao_criar_usuario()
returns trigger language plpgsql security definer
set search_path to 'public','pg_temp'
as $$
declare
  primeiro boolean;
  c public.equipe_convites%rowtype;
begin
  select not exists(select 1 from public.profiles) into primeiro;
  select * into c from public.equipe_convites where email=lower(trim(new.email));
  insert into public.profiles(id,nome,email,foto_url,papel,ativo,area_id,cargo)
  values(
    new.id,
    coalesce(nullif(trim(c.nome),''),nullif(trim(new.raw_user_meta_data->>'nome'),''),nullif(trim(new.raw_user_meta_data->>'full_name'),''),split_part(new.email,'@',1)),
    lower(new.email),
    new.raw_user_meta_data->>'avatar_url',
    case when primeiro then 'admin'::public.papel_usuario when c.email is not null then c.papel else 'membro'::public.papel_usuario end,
    primeiro or c.email is not null,
    c.area_id,
    nullif(trim(c.cargo),'')
  ) on conflict(id) do update set
    nome=excluded.nome,email=excluded.email,papel=excluded.papel,ativo=excluded.ativo,area_id=excluded.area_id,cargo=excluded.cargo;

  if primeiro then
    insert into public.profile_brands(profile_id,brand_id)
    select new.id,b.id from public.brands b where b.ativo on conflict do nothing;
  elsif c.email is not null then
    insert into public.profile_brands(profile_id,brand_id)
    select new.id,b.id from public.brands b
    where b.ativo and (cardinality(c.marcas)=0 or b.id=any(c.marcas))
    on conflict do nothing;
    update public.equipe_convites set aceito_em=coalesce(aceito_em,now()) where email=lower(trim(new.email));
  end if;
  return new;
end
$$;
