-- AllianceOS: data hub inicial da Botanika.
-- Shopify é a fonte operacional principal de pedidos/itens/estoque.
-- Meta Ads e Instagram usam as mesmas tabelas multi-marca para a fase seguinte.

create table if not exists public.integration_sources (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  source text not null check (source in ('shopify','meta_ads','instagram','bling')),
  status text not null default 'pendente' check (status in ('pendente','ok','erro','pausado')),
  last_sync_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, source)
);

create table if not exists public.shopify_orders (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  shopify_order_id text not null,
  numero text,
  financial_status text,
  fulfillment_status text,
  total numeric(14,2) not null default 0,
  subtotal numeric(14,2) not null default 0,
  total_discounts numeric(14,2) not null default 0,
  refunded_amount numeric(14,2) not null default 0,
  currency text not null default 'BRL',
  criado_em timestamptz,
  atualizado_em_shopify timestamptz,
  payment_method text,
  discount_code text,
  cliente_hash text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  utm_fonte text,
  source_category text,
  raw_resumo jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, shopify_order_id)
);
create index if not exists shopify_orders_brand_date_idx on public.shopify_orders (brand_id, criado_em desc);
create index if not exists shopify_orders_brand_status_idx on public.shopify_orders (brand_id, financial_status);
create index if not exists shopify_orders_brand_source_idx on public.shopify_orders (brand_id, source_category);

create table if not exists public.shopify_order_items (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  shopify_order_id text not null,
  line_item_id text not null,
  product_id text,
  variant_id text,
  inventory_item_id text,
  sku text,
  nome_produto text,
  variant_title text,
  quantidade integer not null default 0,
  preco numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_id, line_item_id)
);
create index if not exists shopify_order_items_order_idx on public.shopify_order_items (brand_id, shopify_order_id);
create index if not exists shopify_order_items_sku_idx on public.shopify_order_items (brand_id, sku);

create table if not exists public.shopify_inventory (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  inventory_item_id text not null,
  location_id text not null,
  product_id text,
  variant_id text,
  sku text,
  nome_produto text,
  variant_title text,
  available integer not null default 0,
  atualizado_em_shopify timestamptz,
  updated_at timestamptz not null default now(),
  unique (brand_id, inventory_item_id, location_id)
);
create index if not exists shopify_inventory_brand_idx on public.shopify_inventory (brand_id, available);

create table if not exists public.shopify_sessions_daily (
  brand_id uuid not null references public.brands(id) on delete cascade,
  dia date not null,
  sessions integer not null default 0,
  online_store_visitors integer not null default 0,
  sessions_with_cart_additions integer not null default 0,
  sessions_that_reached_checkout integer not null default 0,
  sessions_that_completed_checkout integer not null default 0,
  conversion_rate numeric(12,6),
  updated_at timestamptz not null default now(),
  primary key (brand_id, dia)
);

create table if not exists public.meta_campaign_insights_daily (
  brand_id uuid not null references public.brands(id) on delete cascade,
  ad_account text not null,
  campaign_id text not null,
  campaign_name text,
  objective text,
  status text,
  dia date not null,
  spend numeric(14,2) not null default 0,
  conversions numeric(14,2) not null default 0,
  revenue numeric(14,2) not null default 0,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  inline_link_clicks bigint not null default 0,
  lp_views bigint not null default 0,
  checkouts bigint not null default 0,
  reach bigint not null default 0,
  cpm numeric(14,4) not null default 0,
  frequency numeric(14,4) not null default 0,
  updated_at timestamptz not null default now(),
  primary key (brand_id, ad_account, campaign_id, dia)
);

create table if not exists public.meta_adset_insights_daily (
  brand_id uuid not null references public.brands(id) on delete cascade,
  ad_account text not null,
  adset_id text not null,
  adset_name text,
  campaign_id text,
  dia date not null,
  spend numeric(14,2) not null default 0,
  conversions numeric(14,2) not null default 0,
  revenue numeric(14,2) not null default 0,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  inline_link_clicks bigint not null default 0,
  lp_views bigint not null default 0,
  checkouts bigint not null default 0,
  reach bigint not null default 0,
  cpm numeric(14,4) not null default 0,
  frequency numeric(14,4) not null default 0,
  updated_at timestamptz not null default now(),
  primary key (brand_id, ad_account, adset_id, dia)
);

create table if not exists public.meta_ad_insights_daily (
  brand_id uuid not null references public.brands(id) on delete cascade,
  ad_account text not null,
  ad_id text not null,
  ad_name text,
  campaign_id text,
  adset_id text,
  adset_name text,
  thumbnail_url text,
  dia date not null,
  spend numeric(14,2) not null default 0,
  conversions numeric(14,2) not null default 0,
  revenue numeric(14,2) not null default 0,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  inline_link_clicks bigint not null default 0,
  lp_views bigint not null default 0,
  checkouts bigint not null default 0,
  reach bigint not null default 0,
  cpm numeric(14,4) not null default 0,
  frequency numeric(14,4) not null default 0,
  updated_at timestamptz not null default now(),
  primary key (brand_id, ad_account, ad_id, dia)
);

create table if not exists public.instagram_snapshots (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  captured_at timestamptz not null,
  followers bigint,
  reach bigint,
  views bigint,
  interactions bigint,
  website_clicks bigint,
  raw_resumo jsonb not null default '{}'::jsonb,
  unique (brand_id, captured_at)
);

alter table public.integration_sources enable row level security;
alter table public.shopify_orders enable row level security;
alter table public.shopify_order_items enable row level security;
alter table public.shopify_inventory enable row level security;
alter table public.shopify_sessions_daily enable row level security;
alter table public.meta_campaign_insights_daily enable row level security;
alter table public.meta_adset_insights_daily enable row level security;
alter table public.meta_ad_insights_daily enable row level security;
alter table public.instagram_snapshots enable row level security;

-- Sem políticas para anon/authenticated por enquanto: o navegador nunca grava
-- nem lê as tabelas cruas. A UI recebe apenas agregados através das APIs do servidor.
