-- AllianceOS round 2 integrity hardening — 2026-09-21
-- Rules: no physical deletion; omission from shared JSON arrays is never deletion.

create schema if not exists app;

create table if not exists public.physical_delete_attempts (
  id bigint generated by default as identity primary key,
  actor_id uuid null,
  origin text not null default 'database',
  entity_type text not null,
  entity_id text not null,
  details jsonb not null default '{}'::jsonb,
  attempted_at timestamptz not null default now()
);

alter table public.physical_delete_attempts enable row level security;

create or replace function app.prevent_physical_delete()
returns trigger
language plpgsql
security definer
set search_path = public, app
as $$
declare
  row_json jsonb := to_jsonb(old);
  entity_id text;
begin
  entity_id := coalesce(row_json->>'id', row_json->>'chave', row_json->>'email', 'sem-id');
  insert into public.physical_delete_attempts(actor_id,origin,entity_type,entity_id,details)
  values(
    app.current_actor_uuid(),
    'database',
    tg_table_name,
    entity_id,
    jsonb_build_object(
      'schema',tg_table_schema,
      'operation',tg_op,
      'blocked',true,
      'current_user',current_user,
      'session_user',session_user
    )
  );
  return null;
end
$$;

create or replace function app.guard_operational_state_items()
returns trigger
language plpgsql
security definer
set search_path = public, app
as $$
declare
  old_item jsonb;
  old_id text;
begin
  if jsonb_typeof(old.valor) <> 'array' or jsonb_typeof(new.valor) <> 'array' then
    return new;
  end if;

  for old_item in select value from jsonb_array_elements(old.valor)
  loop
    old_id := nullif(old_item->>'id','');
    if old_id is null then continue; end if;

    if not exists (
      select 1
      from jsonb_array_elements(new.valor) n(value)
      where n.value->>'id' = old_id
    ) then
      new.valor := new.valor || jsonb_build_array(old_item);
      insert into public.physical_delete_attempts(actor_id,origin,entity_type,entity_id,details)
      values(
        app.current_actor_uuid(),
        'database',
        'operacional_estado_item',
        old_id,
        jsonb_build_object(
          'chave',old.chave,
          'operation','UPDATE_OMISSION',
          'blocked',true,
          'current_user',current_user,
          'session_user',session_user
        )
      );
    end if;
  end loop;

  return new;
end
$$;

drop trigger if exists allianceos_guard_operational_state_items on public.operacional_estado;
create trigger allianceos_guard_operational_state_items
before update of valor on public.operacional_estado
for each row execute function app.guard_operational_state_items();

-- No application/API role may physically delete or truncate operational data.
do $$
declare
  t text;
  tables text[] := array[
    'operacional_estado','task_lists','planning_months','planning_maps','planning_map_nodes',
    'campaign_results','campaign_revenue_sources','alliance_tags','alliance_clients',
    'alliance_automations','notifications','task_action_audit','brands','profiles',
    'equipe_convites','legacy_member_links','legacy_member_names','physical_delete_attempts'
  ];
begin
  foreach t in array tables loop
    if to_regclass('public.'||t) is null then continue; end if;
    execute format('revoke delete, truncate on table public.%I from anon, authenticated, service_role',t);
    execute format('drop trigger if exists allianceos_no_physical_delete on public.%I',t);
    execute format('create trigger allianceos_no_physical_delete before delete on public.%I for each row execute function app.prevent_physical_delete()',t);
  end loop;
end
$$;

-- Remove DELETE RLS policies as defense in depth. Updates/archiving keep their existing policies.
do $$
declare p record;
begin
  for p in
    select schemaname,tablename,policyname
    from pg_policies
    where schemaname='public'
      and cmd='DELETE'
      and tablename in (
        'operacional_estado','task_lists','planning_months','planning_maps','planning_map_nodes',
        'campaign_results','campaign_revenue_sources','alliance_tags','alliance_clients',
        'alliance_automations','notifications','task_action_audit','brands','profiles',
        'equipe_convites','legacy_member_links','legacy_member_names','physical_delete_attempts'
      )
  loop
    execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename);
  end loop;
end
$$;

-- Archive the developer's leftover disappearance test; never delete it.
do $$
declare
  tasks jsonb;
  t jsonb;
  out_tasks jsonb := '[]'::jsonb;
  ts text := to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
begin
  select coalesce(valor,'[]'::jsonb) into tasks
  from public.operacional_estado
  where chave='central.tasks.vitor-gutierrez' and dono is null
  for update;

  if jsonb_typeof(tasks)='array' then
    for t in select value from jsonb_array_elements(tasks)
    loop
      if t->>'title'='TESTE SUMIÇO — vai para em revisão' and nullif(t->>'archivedAt','') is null then
        t := t
          || jsonb_build_object(
            'archivedAt',ts,
            'archivedBy','a02201ec-96d3-433f-b779-b81a4ee10066'
          );
        t := jsonb_set(
          t,
          '{history}',
          jsonb_build_array(jsonb_build_object(
            'at',ts,
            'by','Gestão Alliance',
            'authorId','a02201ec-96d3-433f-b779-b81a4ee10066',
            'authorType','servico',
            'origin','migration',
            'campo','arquivamento',
            'antes',null,
            'depois',ts,
            'text','Tarefa de teste do desenvolvimento arquivada após a auditoria; nenhum dado foi excluído.'
          )) || coalesce(t->'history','[]'::jsonb),
          true
        );
      end if;
      out_tasks := out_tasks || jsonb_build_array(t);
    end loop;

    update public.operacional_estado
    set valor=out_tasks,atualizado_em=now()
    where chave='central.tasks.vitor-gutierrez' and dono is null;
  end if;
end
$$;
