create table if not exists alliance_data.activity_events (
  id bigint generated by default as identity primary key,
  event_key text unique,
  brand_id uuid references public.brands(id),
  occurred_at timestamptz not null default now(),
  event_type text not null,
  entity_type text,
  entity_id text,
  actor_id uuid references auth.users(id),
  origin text not null default 'system',
  summary text,
  before_state jsonb,
  after_state jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists alliance_activity_events_brand_time_idx
  on alliance_data.activity_events(brand_id, occurred_at desc);
create index if not exists alliance_activity_events_entity_idx
  on alliance_data.activity_events(entity_type, entity_id, occurred_at desc);
create index if not exists alliance_activity_events_type_idx
  on alliance_data.activity_events(event_type, occurred_at desc);

create table if not exists alliance_data.decisions (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid references public.brands(id),
  campaign_id text,
  title text not null,
  decision text not null,
  rationale text,
  status text not null default 'active'
    check (status in ('active','reversed','superseded','completed','archived')),
  decided_at timestamptz not null default now(),
  decided_by uuid references auth.users(id),
  expected_outcome text,
  actual_outcome text,
  outcome_checked_at timestamptz,
  source_event_id bigint references alliance_data.activity_events(id),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists alliance_decisions_brand_time_idx
  on alliance_data.decisions(brand_id, decided_at desc);
create index if not exists alliance_decisions_campaign_idx
  on alliance_data.decisions(campaign_id);

create table if not exists alliance_data.learnings (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid references public.brands(id),
  category text,
  title text not null,
  learning text not null,
  status text not null default 'active'
    check (status in ('active','needs_review','superseded','archived')),
  source_type text,
  source_id text,
  evidence jsonb not null default '[]'::jsonb,
  confidence numeric(5,4) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  valid_from timestamptz,
  valid_until timestamptz,
  created_by uuid references auth.users(id),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists alliance_learnings_brand_idx
  on alliance_data.learnings(brand_id, status, created_at desc);
create index if not exists alliance_learnings_source_idx
  on alliance_data.learnings(source_type, source_id);

create table if not exists alliance_data.documents (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid references public.brands(id),
  title text not null,
  document_type text,
  storage_path text,
  external_url text,
  content_hash text,
  extracted_text text,
  source_system text,
  source_id text,
  created_by uuid references auth.users(id),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists alliance_documents_brand_idx
  on alliance_data.documents(brand_id, created_at desc);
create index if not exists alliance_documents_source_idx
  on alliance_data.documents(source_system, source_id);
create index if not exists alliance_documents_hash_idx
  on alliance_data.documents(content_hash);

create table if not exists alliance_data.data_catalog (
  id text primary key,
  domain text not null,
  entity text not null,
  source_schema text not null,
  source_object text not null,
  storage_model text not null
    check (storage_model in ('canonical','mirror','derived','legacy','foundation')),
  brand_scoped boolean not null default true,
  status text not null default 'active'
    check (status in ('active','ready','legacy','planned','deprecated')),
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table alliance_data.activity_events enable row level security;
alter table alliance_data.decisions enable row level security;
alter table alliance_data.learnings enable row level security;
alter table alliance_data.documents enable row level security;
alter table alliance_data.data_catalog enable row level security;

revoke all on alliance_data.activity_events from public, anon, authenticated;
revoke all on alliance_data.decisions from public, anon, authenticated;
revoke all on alliance_data.learnings from public, anon, authenticated;
revoke all on alliance_data.documents from public, anon, authenticated;
revoke all on alliance_data.data_catalog from public, anon, authenticated;

grant select, insert, update, delete on alliance_data.activity_events to service_role;
grant select, insert, update, delete on alliance_data.decisions to service_role;
grant select, insert, update, delete on alliance_data.learnings to service_role;
grant select, insert, update, delete on alliance_data.documents to service_role;
grant select, insert, update, delete on alliance_data.data_catalog to service_role;
grant usage, select on sequence alliance_data.activity_events_id_seq to service_role;

insert into alliance_data.data_catalog
  (id,domain,entity,source_schema,source_object,storage_model,brand_scoped,status,notes)
values
  ('operation.tasks','operation','tasks','alliance_data','tasks','mirror',true,'active','Espelho físico do estado canônico atual; fonte oficial ainda é operacional_estado.'),
  ('operation.campaigns','operation','campaigns','alliance_data','campaigns','mirror',true,'active','Espelho físico do estado canônico atual; fonte oficial ainda é operacional_estado.'),
  ('operation.deliveries','operation','deliveries','alliance_data','deliveries','mirror',true,'active','Espelho físico do estado canônico atual; fonte oficial ainda é operacional_estado.'),
  ('operation.task_lists','operation','task_lists','public','task_lists','canonical',true,'active','Listas relacionais atuais.'),
  ('planning.months','planning','planning_months','public','planning_months','canonical',true,'active','Planejamento mensal por marca.'),
  ('planning.maps','planning','planning_maps','public','planning_maps','canonical',true,'active','Mapas de planejamento por marca.'),
  ('campaign.results','performance','campaign_results','public','campaign_results','canonical',true,'active','Resultados de campanhas.'),
  ('campaign.versions','history','campaign_versions','public','campaign_versions','canonical',true,'active','Versionamento de campanhas.'),
  ('commerce.orders','commerce','orders','public','shopify_orders','foundation',true,'ready','Estrutura multi-marca pronta para sincronização Shopify.'),
  ('commerce.items','commerce','order_items','public','shopify_order_items','foundation',true,'ready','Itens de pedidos Shopify.'),
  ('commerce.inventory','commerce','inventory','public','shopify_inventory','foundation',true,'ready','Estoque Shopify por marca.'),
  ('ads.campaign_daily','marketing','campaign_daily','public','meta_campaign_insights_daily','foundation',true,'ready','Métricas diárias de campanhas Meta.'),
  ('ads.adset_daily','marketing','adset_daily','public','meta_adset_insights_daily','foundation',true,'ready','Métricas diárias de conjuntos Meta.'),
  ('ads.ad_daily','marketing','ad_daily','public','meta_ad_insights_daily','foundation',true,'ready','Métricas diárias de anúncios Meta.'),
  ('social.instagram','marketing','instagram_snapshots','public','instagram_snapshots','foundation',true,'ready','Snapshots de Instagram por marca.'),
  ('knowledge.decisions','knowledge','decisions','alliance_data','decisions','foundation',true,'ready','Memória estruturada de decisões.'),
  ('knowledge.learnings','knowledge','learnings','alliance_data','learnings','foundation',true,'ready','Aprendizados operacionais e evidências.'),
  ('knowledge.documents','knowledge','documents','alliance_data','documents','foundation',true,'ready','Metadados e texto extraído de documentos.'),
  ('history.events','history','activity_events','alliance_data','activity_events','foundation',true,'active','Linha do tempo unificada de eventos.')
on conflict (id) do update set
  domain=excluded.domain,
  entity=excluded.entity,
  source_schema=excluded.source_schema,
  source_object=excluded.source_object,
  storage_model=excluded.storage_model,
  brand_scoped=excluded.brand_scoped,
  status=excluded.status,
  notes=excluded.notes,
  updated_at=clock_timestamp();

insert into alliance_data.activity_events (
  event_key, brand_id, occurred_at, event_type, entity_type, entity_id,
  actor_id, origin, summary, before_state, after_state, metadata
)
select
  'campaign-version:' || cv.id::text,
  cv.brand_id,
  cv.created_at,
  'campaign_version',
  'campaign',
  cv.campaign_id,
  cv.actor_id,
  cv.origin,
  cv.note,
  cv.previous_snapshot,
  cv.snapshot,
  jsonb_build_object(
    'changed_keys', cv.changed_keys,
    'is_original', cv.is_original,
    'month_ref', cv.month_ref,
    'brand', cv.brand
  )
from public.campaign_versions cv
on conflict (event_key) do nothing;

insert into alliance_data.activity_events (
  event_key, occurred_at, event_type, entity_type, entity_id,
  actor_id, origin, summary, metadata
)
select
  'task-audit:' || a.id::text,
  a.created_at,
  a.action,
  a.entity_type,
  a.entity_id,
  a.actor_id,
  a.origin,
  a.action,
  a.details || jsonb_build_object('actor_snapshot',a.actor_snapshot)
from public.task_action_audit a
on conflict (event_key) do nothing;

create or replace view alliance_data.knowledge_overview
with (security_invoker = true)
as
select
  b.id as brand_id,
  b.nome as brand_name,
  (select count(*) from alliance_data.decisions d where d.brand_id=b.id and d.status<>'archived')::bigint as decisions,
  (select count(*) from alliance_data.learnings l where l.brand_id=b.id and l.status='active')::bigint as active_learnings,
  (select count(*) from alliance_data.documents x where x.brand_id=b.id)::bigint as documents,
  (select count(*) from alliance_data.activity_events e where e.brand_id=b.id)::bigint as events
from public.brands b
where b.ativo;

revoke all on alliance_data.knowledge_overview from public, anon, authenticated;
grant select on alliance_data.knowledge_overview to service_role;
