create schema if not exists private;

create table if not exists public.access_center_entries (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  category text not null default 'Outros',
  name text not null,
  description text,
  kind text not null default 'account' check (kind in ('account','integration','technical','document','pixel')),
  status text not null default 'active' check (status in ('active','cancelled','archived')),
  owner text,
  payment_method text,
  cost_amount numeric(14,2),
  cost_label text,
  purchase_date date,
  renewal_day integer check (renewal_day is null or renewal_day between 1 and 31),
  renewal_date date,
  recurrence text,
  username text,
  recovery_contact text,
  login_url text,
  two_factor_enabled boolean,
  notes text,
  sort_order integer not null default 0,
  source_sheet text,
  source_row integer,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.access_center_secrets (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.access_center_entries(id) on delete cascade,
  label text not null,
  secret_kind text not null default 'password',
  vault_secret_id uuid not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.access_center_audit (
  id bigint generated by default as identity primary key,
  entry_id uuid references public.access_center_entries(id) on delete set null,
  brand_id uuid references public.brands(id) on delete set null,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists access_center_entries_brand_status_idx
  on public.access_center_entries(brand_id,status,sort_order,name);
create index if not exists access_center_entries_category_idx
  on public.access_center_entries(brand_id,category);
create index if not exists access_center_secrets_entry_idx
  on public.access_center_secrets(entry_id,sort_order);
create index if not exists access_center_audit_entry_created_idx
  on public.access_center_audit(entry_id,created_at desc);

alter table public.access_center_entries enable row level security;
alter table public.access_center_secrets enable row level security;
alter table public.access_center_audit enable row level security;

create or replace function private.access_center_can_view(p_brand_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id=(select auth.uid()) and p.ativo=true
      and (
        p.papel::text='admin'
        or exists (
          select 1 from public.profile_brands pb
          where pb.profile_id=p.id and pb.brand_id=p_brand_id and pb.ativo=true
        )
      )
  );
$$;

create or replace function private.access_center_can_manage(p_brand_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id=(select auth.uid()) and p.ativo=true
      and p.papel::text in ('admin','gestor')
      and (
        p.papel::text='admin'
        or exists (
          select 1 from public.profile_brands pb
          where pb.profile_id=p.id and pb.brand_id=p_brand_id and pb.ativo=true
        )
      )
  );
$$;

drop policy if exists access_center_entries_select on public.access_center_entries;
create policy access_center_entries_select
on public.access_center_entries for select to authenticated
using ((select private.access_center_can_view(brand_id)));

revoke all on public.access_center_entries from anon;
revoke insert,update,delete on public.access_center_entries from authenticated;
grant select on public.access_center_entries to authenticated;
revoke all on public.access_center_secrets from anon,authenticated;
revoke all on public.access_center_audit from anon,authenticated;

create or replace function public.access_center_list(p_brand_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path=''
as $$
declare result jsonb;
begin
  if (select auth.uid()) is null then raise exception 'Sessão inválida'; end if;
  select coalesce(jsonb_agg(item order by item->>'category',(item->>'sort_order')::int,item->>'name'),'[]'::jsonb)
  into result
  from (
    select jsonb_build_object(
      'id',e.id,'brand_id',e.brand_id,'brand_name',b.nome,'category',e.category,'name',e.name,
      'description',e.description,'kind',e.kind,'status',e.status,'owner',e.owner,'payment_method',e.payment_method,
      'cost_amount',e.cost_amount,'cost_label',e.cost_label,'purchase_date',e.purchase_date,'renewal_day',e.renewal_day,
      'renewal_date',e.renewal_date,'recurrence',e.recurrence,'username',e.username,'recovery_contact',e.recovery_contact,
      'login_url',e.login_url,'two_factor_enabled',e.two_factor_enabled,'notes',e.notes,'sort_order',e.sort_order,
      'source_sheet',e.source_sheet,'source_row',e.source_row,
      'can_manage',private.access_center_can_manage(e.brand_id),
      'secrets',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',s.id,'label',s.label,'kind',s.secret_kind,'sort_order',s.sort_order
        ) order by s.sort_order,s.label)
        from public.access_center_secrets s where s.entry_id=e.id
      ),'[]'::jsonb)
    ) item
    from public.access_center_entries e
    join public.brands b on b.id=e.brand_id
    where e.status<>'archived'
      and (p_brand_id is null or e.brand_id=p_brand_id)
      and private.access_center_can_view(e.brand_id)
  ) q;
  return coalesce(result,'[]'::jsonb);
end;
$$;

create or replace function public.access_center_reveal_secret(p_secret_id uuid)
returns text language plpgsql volatile security definer set search_path=''
as $$
declare
  v_entry public.access_center_entries%rowtype;
  v_vault_id uuid;
  v_secret text;
begin
  select e.* into v_entry
  from public.access_center_secrets s
  join public.access_center_entries e on e.id=s.entry_id
  where s.id=p_secret_id and e.status<>'archived';
  if not found then raise exception 'Credencial não encontrada'; end if;

  select s.vault_secret_id into v_vault_id
  from public.access_center_secrets s
  where s.id=p_secret_id and s.entry_id=v_entry.id;

  if not private.access_center_can_manage(v_entry.brand_id) then
    raise exception 'Você não tem permissão para revelar credenciais desta marca';
  end if;

  select ds.decrypted_secret into v_secret
  from vault.decrypted_secrets ds where ds.id=v_vault_id;

  insert into public.access_center_audit(entry_id,brand_id,actor_id,action,metadata)
  values(v_entry.id,v_entry.brand_id,(select auth.uid()),'reveal_secret',jsonb_build_object('secret_id',p_secret_id));
  return v_secret;
end;
$$;

create or replace function public.access_center_save_entry(p_entry jsonb)
returns uuid language plpgsql volatile security definer set search_path=''
as $$
declare v_id uuid; v_brand uuid;
begin
  v_id:=nullif(p_entry->>'id','')::uuid;
  v_brand:=nullif(p_entry->>'brand_id','')::uuid;
  if v_brand is null then raise exception 'Marca obrigatória'; end if;
  if not private.access_center_can_manage(v_brand) then raise exception 'Você não tem permissão para editar acessos desta marca'; end if;
  if nullif(trim(p_entry->>'name'),'') is null then raise exception 'Nome obrigatório'; end if;

  if v_id is null then
    insert into public.access_center_entries(
      brand_id,category,name,description,kind,status,owner,payment_method,cost_amount,cost_label,purchase_date,
      renewal_day,renewal_date,recurrence,username,recovery_contact,login_url,two_factor_enabled,notes,sort_order,
      created_by,updated_by
    ) values(
      v_brand,coalesce(nullif(trim(p_entry->>'category'),''),'Outros'),trim(p_entry->>'name'),
      nullif(trim(p_entry->>'description'),''),coalesce(nullif(p_entry->>'kind',''),'account'),
      coalesce(nullif(p_entry->>'status',''),'active'),nullif(trim(p_entry->>'owner'),''),
      nullif(trim(p_entry->>'payment_method'),''),nullif(p_entry->>'cost_amount','')::numeric,
      nullif(trim(p_entry->>'cost_label'),''),nullif(p_entry->>'purchase_date','')::date,
      nullif(p_entry->>'renewal_day','')::integer,nullif(p_entry->>'renewal_date','')::date,
      nullif(trim(p_entry->>'recurrence'),''),nullif(trim(p_entry->>'username'),''),
      nullif(trim(p_entry->>'recovery_contact'),''),nullif(trim(p_entry->>'login_url'),''),
      case when p_entry ? 'two_factor_enabled' and p_entry->'two_factor_enabled'<>'null'::jsonb
        then (p_entry->>'two_factor_enabled')::boolean else null end,
      nullif(trim(p_entry->>'notes'),''),coalesce(nullif(p_entry->>'sort_order','')::integer,0),
      (select auth.uid()),(select auth.uid())
    ) returning id into v_id;
    insert into public.access_center_audit(entry_id,brand_id,actor_id,action)
    values(v_id,v_brand,(select auth.uid()),'create_entry');
  else
    if not exists(select 1 from public.access_center_entries e where e.id=v_id and e.brand_id=v_brand)
      then raise exception 'Acesso não encontrado'; end if;
    update public.access_center_entries set
      category=coalesce(nullif(trim(p_entry->>'category'),''),category),
      name=coalesce(nullif(trim(p_entry->>'name'),''),name),
      description=case when p_entry ? 'description' then nullif(trim(p_entry->>'description'),'') else description end,
      kind=coalesce(nullif(p_entry->>'kind',''),kind),
      status=coalesce(nullif(p_entry->>'status',''),status),
      owner=case when p_entry ? 'owner' then nullif(trim(p_entry->>'owner'),'') else owner end,
      payment_method=case when p_entry ? 'payment_method' then nullif(trim(p_entry->>'payment_method'),'') else payment_method end,
      cost_amount=case when p_entry ? 'cost_amount' then nullif(p_entry->>'cost_amount','')::numeric else cost_amount end,
      cost_label=case when p_entry ? 'cost_label' then nullif(trim(p_entry->>'cost_label'),'') else cost_label end,
      purchase_date=case when p_entry ? 'purchase_date' then nullif(p_entry->>'purchase_date','')::date else purchase_date end,
      renewal_day=case when p_entry ? 'renewal_day' then nullif(p_entry->>'renewal_day','')::integer else renewal_day end,
      renewal_date=case when p_entry ? 'renewal_date' then nullif(p_entry->>'renewal_date','')::date else renewal_date end,
      recurrence=case when p_entry ? 'recurrence' then nullif(trim(p_entry->>'recurrence'),'') else recurrence end,
      username=case when p_entry ? 'username' then nullif(trim(p_entry->>'username'),'') else username end,
      recovery_contact=case when p_entry ? 'recovery_contact' then nullif(trim(p_entry->>'recovery_contact'),'') else recovery_contact end,
      login_url=case when p_entry ? 'login_url' then nullif(trim(p_entry->>'login_url'),'') else login_url end,
      two_factor_enabled=case
        when p_entry ? 'two_factor_enabled' and p_entry->'two_factor_enabled'<>'null'::jsonb then (p_entry->>'two_factor_enabled')::boolean
        when p_entry ? 'two_factor_enabled' then null else two_factor_enabled end,
      notes=case when p_entry ? 'notes' then nullif(trim(p_entry->>'notes'),'') else notes end,
      sort_order=case when p_entry ? 'sort_order' then coalesce(nullif(p_entry->>'sort_order','')::integer,0) else sort_order end,
      updated_by=(select auth.uid()),updated_at=now()
    where id=v_id;
    insert into public.access_center_audit(entry_id,brand_id,actor_id,action)
    values(v_id,v_brand,(select auth.uid()),'update_entry');
  end if;
  return v_id;
end;
$$;

create or replace function public.access_center_set_secret(
  p_entry_id uuid,p_secret_id uuid default null,p_label text default 'Senha',
  p_kind text default 'password',p_value text default null
)
returns uuid language plpgsql volatile security definer set search_path=''
as $$
declare
  v_entry public.access_center_entries%rowtype;
  v_secret_id uuid; v_vault_id uuid; v_name text;
begin
  select * into v_entry from public.access_center_entries where id=p_entry_id and status<>'archived';
  if not found then raise exception 'Acesso não encontrado'; end if;
  if not private.access_center_can_manage(v_entry.brand_id) then raise exception 'Você não tem permissão para editar credenciais desta marca'; end if;
  if nullif(p_value,'') is null then raise exception 'Valor da credencial obrigatório'; end if;
  if nullif(trim(p_label),'') is null then raise exception 'Rótulo obrigatório'; end if;

  if p_secret_id is null then
    v_secret_id:=gen_random_uuid();
    v_name:='access-center/'||v_entry.brand_id::text||'/'||p_entry_id::text||'/'||v_secret_id::text;
    select vault.create_secret(p_value,v_name,'AllianceOS Central de Acessos · '||trim(p_label)) into v_vault_id;
    insert into public.access_center_secrets(id,entry_id,label,secret_kind,vault_secret_id)
    values(v_secret_id,p_entry_id,trim(p_label),coalesce(nullif(trim(p_kind),''),'password'),v_vault_id);
  else
    select id,vault_secret_id into v_secret_id,v_vault_id
    from public.access_center_secrets where id=p_secret_id and entry_id=p_entry_id;
    if not found then raise exception 'Credencial não encontrada'; end if;
    perform vault.update_secret(v_vault_id,p_value,null,'AllianceOS Central de Acessos · '||trim(p_label));
    update public.access_center_secrets
    set label=trim(p_label),secret_kind=coalesce(nullif(trim(p_kind),''),secret_kind),updated_at=now()
    where id=v_secret_id;
  end if;

  insert into public.access_center_audit(entry_id,brand_id,actor_id,action,metadata)
  values(p_entry_id,v_entry.brand_id,(select auth.uid()),
    case when p_secret_id is null then 'create_secret' else 'update_secret' end,
    jsonb_build_object('secret_id',v_secret_id,'label',p_label));
  return v_secret_id;
end;
$$;

create or replace function public.access_center_archive_entry(p_entry_id uuid)
returns void language plpgsql volatile security definer set search_path=''
as $$
declare v_brand uuid;
begin
  select brand_id into v_brand from public.access_center_entries where id=p_entry_id;
  if v_brand is null then raise exception 'Acesso não encontrado'; end if;
  if not private.access_center_can_manage(v_brand) then raise exception 'Você não tem permissão para arquivar acessos desta marca'; end if;
  update public.access_center_entries set status='archived',updated_by=(select auth.uid()),updated_at=now() where id=p_entry_id;
  insert into public.access_center_audit(entry_id,brand_id,actor_id,action)
  values(p_entry_id,v_brand,(select auth.uid()),'archive_entry');
end;
$$;

revoke all on function public.access_center_list(uuid) from public,anon;
revoke all on function public.access_center_reveal_secret(uuid) from public,anon;
revoke all on function public.access_center_save_entry(jsonb) from public,anon;
revoke all on function public.access_center_set_secret(uuid,uuid,text,text,text) from public,anon;
revoke all on function public.access_center_archive_entry(uuid) from public,anon;
grant execute on function public.access_center_list(uuid) to authenticated;
grant execute on function public.access_center_reveal_secret(uuid) to authenticated;
grant execute on function public.access_center_save_entry(jsonb) to authenticated;
grant execute on function public.access_center_set_secret(uuid,uuid,text,text,text) to authenticated;
grant execute on function public.access_center_archive_entry(uuid) to authenticated;
