const SB='https://lpnyrzsdiyzjnhovpduk.supabase.co'; let K='';
async function key(){if(K)return K; const r=await fetch(`${SB}/functions/v1/public-config`); if(!r.ok)throw Error('configuração do Supabase indisponível'); K=String((await r.json()).anon||''); if(!K)throw Error('chave pública indisponível'); return K}
function send(res,s,b){res.setHeader('Cache-Control','no-store');return res.status(s).json(b)}
async function user(token){if(!token)return null; const k=await key(),r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:k,Authorization:`Bearer ${token}`}}); return r.ok?await r.json():null}
async function h(token){return {apikey:await key(),Authorization:`Bearer ${token}`,'Content-Type':'application/json'}}
function safeUrl(v){try{const u=new URL(String(v||'').trim().replace(/^webcal:/,'https:')); if(u.protocol!=='https:')return null; const ok=/(^|\.)(google\.com|office365\.com|office\.com|live\.com|icloud\.com|notion\.so)$/i.test(u.hostname)||/calendar\.google\.com$/i.test(u.hostname); return ok?u.toString():null}catch{return null}}
function unfold(s){return s.replace(/\r?\n[ \t]/g,'').split(/\r?\n/)}
function dt(v){if(!v)return null; const z=v.replace(/^.*:/,''); if(/^\d{8}T\d{6}Z$/.test(z))return new Date(`${z.slice(0,4)}-${z.slice(4,6)}-${z.slice(6,8)}T${z.slice(9,11)}:${z.slice(11,13)}:${z.slice(13,15)}Z`); if(/^\d{8}T\d{6}$/.test(z))return new Date(`${z.slice(0,4)}-${z.slice(4,6)}-${z.slice(6,8)}T${z.slice(9,11)}:${z.slice(11,13)}:${z.slice(13,15)}`); if(/^\d{8}$/.test(z))return new Date(`${z.slice(0,4)}-${z.slice(4,6)}-${z.slice(6,8)}T00:00:00`); return new Date(z)}
function parseIcs(text){const out=[]; let e=null; for(const line of unfold(text)){if(line==='BEGIN:VEVENT'){e={};continue} if(line==='END:VEVENT'){if(e?.inicio){out.push(e)} e=null;continue} if(!e)continue; const i=line.indexOf(':'); if(i<0)continue; const n=line.slice(0,i).split(';')[0].toUpperCase(),v=line.slice(i+1).replace(/\\n/g,'\n').replace(/\\,/g,','); if(n==='SUMMARY')e.titulo=v; else if(n==='DTSTART')e.inicio=dt(line)?.toISOString(); else if(n==='DTEND')e.fim=dt(line)?.toISOString(); else if(n==='LOCATION')e.local=v; else if(n==='DESCRIPTION')e.descricao=v.slice(0,1000); else if(n==='UID')e.id=v} const now=Date.now(),a=now-7*864e5,b=now+45*864e5; return out.filter(x=>{const t=Date.parse(x.inicio);return t>=a&&t<=b}).sort((a,b)=>Date.parse(a.inicio)-Date.parse(b.inicio)).slice(0,500)}
async function fetchCal(url){const r=await fetch(url,{headers:{Accept:'text/calendar'},signal:AbortSignal.timeout?.(12000)}); if(!r.ok)throw Error(`calendário respondeu ${r.status}`); const t=await r.text(); if(t.length>6*1024*1024||!t.includes('BEGIN:VCALENDAR'))throw Error('endereço não devolve um calendário iCal'); return parseIcs(t)}
export default async function handler(req,res){try{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim(),u=await user(token); if(!u?.id)return send(res,401,{erro:'entre na AllianceOS para ver a agenda'}); const headers=await h(token),body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}); if(req.method==='DELETE'||(req.method==='POST'&&body.acao==='desligar')){await fetch(`${SB}/rest/v1/agenda_fonte?dono=eq.${u.id}`,{method:'DELETE',headers});return send(res,200,{ligado:false})} if(req.method==='POST'){const url=safeUrl(body.url); if(!url)return send(res,400,{erro:'use um endereço iCal https do Google, Outlook, iCloud ou Notion'}); const eventos=await fetchCal(url); await fetch(`${SB}/rest/v1/agenda_fonte?on_conflict=dono`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates'},body:JSON.stringify({dono:u.id,url,apelido:String(body.apelido||'').slice(0,60)||null,eventos,lido_em:new Date().toISOString(),erro:null})}); return send(res,200,{ligado:true,eventos,lido_em:new Date().toISOString()})} const r=await fetch(`${SB}/rest/v1/agenda_fonte?select=*`,{headers}); if(!r.ok)throw Error('não foi possível ler a agenda'); const f=(await r.json())[0]; if(!f)return send(res,200,{ligado:false,eventos:[]}); const stale=!f.lido_em||Date.now()-Date.parse(f.lido_em)>10*60e3,force=new URL(req.url,'http://x').searchParams.get('forcar')==='1'; if(stale||force){try{const eventos=await fetchCal(f.url),lido_em=new Date().toISOString(); await fetch(`${SB}/rest/v1/agenda_fonte?on_conflict=dono`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates'},body:JSON.stringify({dono:u.id,url:f.url,apelido:f.apelido,eventos,lido_em,erro:null})}); return send(res,200,{ligado:true,apelido:f.apelido,eventos,lido_em})}catch(e){return send(res,200,{ligado:true,apelido:f.apelido,eventos:f.eventos||[],lido_em:f.lido_em,erro:String(e.message||e)})}} return send(res,200,{ligado:true,apelido:f.apelido,eventos:f.eventos||[],lido_em:f.lido_em,erro:f.erro||null})}catch(e){console.error('[agenda]',e);return send(res,500,{erro:String(e.message||e).slice(0,240)})}}
