import {createSign} from 'node:crypto';
const SB='https://lpnyrzsdiyzjnhovpduk.supabase.co';let K='',GT={token:'',exp:0};
async function key(){if(K)return K;const r=await fetch(`${SB}/functions/v1/public-config`);if(!r.ok)throw Error('configuração do Supabase indisponível');K=String((await r.json()).anon||'');if(!K)throw Error('chave pública indisponível');return K}
function send(res,s,b){res.setHeader('Cache-Control','no-store');return res.status(s).json(b)}
async function user(t){if(!t)return null;const k=await key(),r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:k,Authorization:`Bearer ${t}`}});return r.ok?await r.json():null}
async function brand(nome,t){const k=await key(),r=await fetch(`${SB}/rest/v1/painel_marcas?marca=eq.${encodeURIComponent(nome)}&select=marca,drive_pasta,ativo`,{headers:{apikey:k,Authorization:`Bearer ${t}`}});if(!r.ok)return null;const m=(await r.json())[0];return m?.ativo?m:null}
function account(){const raw=process.env.GOOGLE_DRIVE_SA||'';if(!raw.trim())return null;try{return JSON.parse(raw)}catch{try{return JSON.parse(Buffer.from(raw,'base64').toString('utf8'))}catch{return null}}}
const b64=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
async function googleToken(){if(GT.token&&Date.now()<GT.exp-60000)return GT.token;const a=account();if(!a?.client_email||!a?.private_key)throw Object.assign(Error('GOOGLE_DRIVE_SA não configurada'),{status:503});const now=Math.floor(Date.now()/1000),h=b64({alg:'RS256',typ:'JWT'}),p=b64({iss:a.client_email,scope:'https://www.googleapis.com/auth/drive.readonly',aud:a.token_uri||'https://oauth2.googleapis.com/token',iat:now,exp:now+3500}),sig=createSign('RSA-SHA256').update(`${h}.${p}`).sign(a.private_key,'base64url'),assertion=`${h}.${p}.${sig}`,r=await fetch(a.token_uri||'https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});const j=await r.json();if(!r.ok||!j.access_token)throw Error(j.error_description||'falha ao autenticar no Google Drive');GT={token:j.access_token,exp:Date.now()+(Number(j.expires_in)||3600)*1000};return GT.token}
async function g(path,params={}){const u=new URL(`https://www.googleapis.com/drive/v3/${path}`);for(const[k,v]of Object.entries(params))if(v!=null&&v!=='')u.searchParams.set(k,v);const r=await fetch(u,{headers:{Authorization:`Bearer ${await googleToken()}`}});const j=await r.json();if(!r.ok)throw Error(j?.error?.message||`Google Drive ${r.status}`);return j}
export default async function handler(req,res){try{const tok=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim(),u=await user(tok);if(!u?.id)return send(res,401,{erro:'entre na AllianceOS para ver os arquivos'});const q=Object.fromEntries(new URL(req.url,'http://x').searchParams),nome=q.marca||'Botanika',m=await brand(nome,tok);if(!m)return send(res,404,{erro:`marca desconhecida: ${nome}`});if(!m.drive_pasta)return send(res,200,{configurado:false,marca:nome,arquivos:[],erro:`Drive da ${nome} ainda não foi conectado`});if(!account())return send(res,200,{configurado:false,marca:nome,arquivos:[],erro:'conta de serviço do Google Drive ainda não configurada'});const parent=q.pasta||m.drive_pasta,busca=String(q.q||'').trim().replace(/'/g,"\\'");let where=`'${parent}' in parents and trashed=false`;if(busca)where+=` and name contains '${busca}'`;const d=await g('files',{q:where,fields:'files(id,name,mimeType,iconLink,webViewLink,thumbnailLink,modifiedTime,size)',orderBy:'folder,name',pageSize:'100',supportsAllDrives:'true',includeItemsFromAllDrives:'true'});return send(res,200,{configurado:true,marca:nome,pasta:parent,arquivos:d.files||[]})}catch(e){console.error('[drive]',e);return send(res,e.status||502,{erro:String(e.message||e).slice(0,250)})}}
