import {requireAllianceUser,authError} from './_lib/auth.mjs';
import {createSign} from 'node:crypto';

const BRAND='https://lpnyrzsdiyzjnhovpduk.supabase.co/functions/v1/public-brand';
const CONFIG='https://lpnyrzsdiyzjnhovpduk.supabase.co/functions/v1/public-config';
const DELIVERY_BUCKET='alliance-deliveries';
const PASTA='application/vnd.google-apps.folder';
const CAMPOS='id,name,mimeType,iconLink,webViewLink,thumbnailLink,modifiedTime,size,owners(displayName)';
function send(res,status,body){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');return res.status(status).send(JSON.stringify(body))}
async function marca(nome){const r=await fetch(`${BRAND}?marca=${encodeURIComponent(nome)}`,{cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(j.erro||`marca HTTP ${r.status}`),{status:r.status});return j}
async function salvarPasta(nome,pasta){const r=await fetch(BRAND,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({marca:nome,drive_pasta:pasta})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(j.erro||`configuração HTTP ${r.status}`),{status:r.status});return j}
function conta(){const cru=process.env.GOOGLE_DRIVE_SA||'';if(!cru.trim())return null;const texto=cru.trim().startsWith('{')?cru:Buffer.from(cru,'base64').toString('utf8');const sa=JSON.parse(texto);if(!sa.client_email||!sa.private_key)throw Error('a chave da conta de serviço está incompleta');return sa}
const b64u=t=>Buffer.from(t).toString('base64url');
let guardado={token:null,ate:0};
async function token(){if(guardado.token&&Date.now()<guardado.ate-60000)return guardado.token;const sa=conta();if(!sa)throw Object.assign(Error('sem conta de serviço configurada'),{faltaChave:true});const agora=Math.floor(Date.now()/1000),cab=b64u(JSON.stringify({alg:'RS256',typ:'JWT'})),corpo=b64u(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/drive',aud:sa.token_uri||'https://oauth2.googleapis.com/token',iat:agora,exp:agora+3600})),assina=createSign('RSA-SHA256');assina.update(`${cab}.${corpo}`);const jwt=`${cab}.${corpo}.${assina.sign(sa.private_key).toString('base64url')}`,r=await fetch(sa.token_uri||'https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})}),j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw Error(j.error_description||j.error||`Google recusou a chave (HTTP ${r.status})`);guardado={token:j.access_token,ate:Date.now()+(j.expires_in||3600)*1000};return guardado.token}
async function drive(caminho,params={}){const u=new URL(`https://www.googleapis.com/drive/v3/${caminho}`);for(const[k,v]of Object.entries(params))if(v!=null&&v!=='')u.searchParams.set(k,String(v));u.searchParams.set('supportsAllDrives','true');const r=await fetch(u,{headers:{Authorization:`Bearer ${await token()}`}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(j?.error?.message||`Google Drive ${r.status}`),{status:r.status});return j}
async function dentroDe(id,raiz){if(!id||id===raiz)return true;let atual=id;for(let i=0;i<18;i++){const f=await drive(`files/${encodeURIComponent(atual)}`,{fields:'id,parents'}),pais=f.parents||[];if(!pais.length)return false;if(pais.includes(raiz))return true;atual=pais[0]}return false}
const aspas=t=>String(t).replace(/\\/g,'\\\\').replace(/'/g,"\\'");
let cfgCache=null;
async function cfg(){if(cfgCache)return cfgCache;const r=await fetch(CONFIG,{cache:'no-store'});if(!r.ok)throw Error('configuração do armazenamento indisponível');cfgCache=await r.json();return cfgCache}
const encodePath=p=>String(p||'').split('/').filter(Boolean).map(encodeURIComponent).join('/');
async function stagingObject(auth,bucket,path){if(bucket!==DELIVERY_BUCKET)throw Object.assign(Error('bucket de entrega inválido'),{status:400});const c=await cfg(),url=`${c.url}/storage/v1/object/authenticated/${encodeURIComponent(bucket)}/${encodePath(path)}`;const r=await fetch(url,{headers:{apikey:c.anon,Authorization:auth},cache:'no-store'});if(!r.ok){const msg=await r.text().catch(()=>(''));throw Object.assign(Error(msg||`arquivo temporário HTTP ${r.status}`),{status:r.status})}return {response:r,config:c}}
async function apagarStaging(auth,c,bucket,path){try{await fetch(`${c.url}/storage/v1/object/${encodeURIComponent(bucket)}/${encodePath(path)}`,{method:'DELETE',headers:{apikey:c.anon,Authorization:auth}})}catch{}}
async function existentePorUploadId(pasta,uploadId){if(!uploadId)return null;const q=`'${aspas(pasta)}' in parents and appProperties has { key='allianceUploadId' and value='${aspas(uploadId)}' } and trashed = false`;const list=await drive('files',{q,fields:'files(id,name,mimeType,webViewLink,size,parents)',pageSize:'2',includeItemsFromAllDrives:'true',corpora:'allDrives'});return list.files?.[0]||null}
async function enviarAoDrive({pasta,nome,mime,size,uploadId,storageResponse}){const existing=await existentePorUploadId(pasta,uploadId);if(existing)return existing;const folder=await drive(`files/${encodeURIComponent(pasta)}`,{fields:'id,name,mimeType,capabilities(canAddChildren)'});if(folder.mimeType!==PASTA)throw Object.assign(Error('o destino escolhido não é uma pasta do Drive'),{status:400});if(folder.capabilities&&folder.capabilities.canAddChildren===false)throw Object.assign(Error('a conta do AllianceOS não pode adicionar arquivos nesta pasta'),{status:403});const init=new URL('https://www.googleapis.com/upload/drive/v3/files');init.searchParams.set('uploadType','resumable');init.searchParams.set('supportsAllDrives','true');init.searchParams.set('fields','id,name,mimeType,webViewLink,size,parents');const auth=`Bearer ${await token()}`;const start=await fetch(init,{method:'POST',headers:{Authorization:auth,'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Type':mime||'application/octet-stream','X-Upload-Content-Length':String(size||0)},body:JSON.stringify({name:nome,parents:[pasta],appProperties:{allianceUploadId:String(uploadId||''),allianceOS:'delivery'}})});if(!start.ok){const j=await start.json().catch(()=>({}));throw Object.assign(Error(j?.error?.message||`Google Drive ${start.status}`),{status:start.status})}const location=start.headers.get('location');if(!location)throw Error('Google não abriu uma sessão de upload');const put=await fetch(location,{method:'PUT',headers:{Authorization:auth,'Content-Type':mime||'application/octet-stream','Content-Length':String(size||0)},body:storageResponse.body,duplex:'half'});const file=await put.json().catch(()=>({}));if(!put.ok)throw Object.assign(Error(file?.error?.message||`upload Google Drive ${put.status}`),{status:put.status});if(file.webViewLink)return file;return drive(`files/${encodeURIComponent(file.id)}`,{fields:'id,name,mimeType,webViewLink,size,parents'})}
async function copiarStorage(body,session){const nome=String(body.marca||'').trim(),m=await marca(nome);if(!m.drive_pasta)throw Object.assign(Error(`A ${m.marca} ainda não tem a raiz do Drive configurada.`),{status:409});const raiz=m.drive_pasta,pasta=String(body.pasta||'').trim();if(!pasta)throw Object.assign(Error('escolha uma pasta de destino'),{status:400});if(!(await dentroDe(pasta,raiz)))throw Object.assign(Error('essa pasta não pertence ao Drive configurado para esta marca'),{status:403});const bucket=String(body.bucket||''),path=String(body.path||'').trim();if(!path||!path.startsWith(String(session.user.id)+'/'))throw Object.assign(Error('arquivo temporário inválido para este usuário'),{status:403});const staged=await stagingObject(session.authorization,bucket,path);const tamanho=Number(body.size||staged.response.headers.get('content-length')||0);const mime=String(body.mime_type||staged.response.headers.get('content-type')||'application/octet-stream').split(';')[0];const arquivo=await enviarAoDrive({pasta,nome:String(body.name||'arquivo'),mime,size:tamanho,uploadId:String(body.upload_id||path),storageResponse:staged.response});await apagarStaging(session.authorization,staged.config,bucket,path);return {id:arquivo.id,nome:arquivo.name,tipo:arquivo.mimeType,link:arquivo.webViewLink||`https://drive.google.com/file/d/${arquivo.id}/view`,tamanho:arquivo.size?+arquivo.size:tamanho,pasta,raiz}}
export default async function handler(req,res){try{const session=await requireAllianceUser(req);const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});
  if(req.method==='POST'&&body.action==='copy_storage'){const arquivo=await copiarStorage(body,session);return send(res,200,{ok:true,arquivo})}
  if(req.method==='POST'){const nome=String(body.marca||'Botanika'),raw=String(body.drive_pasta||body.pasta||'').trim(),limpo=raw.replace(/^https?:\/\/drive\.google\.com\/drive\/(u\/\d+\/)?folders\//,'').split(/[?#]/)[0].trim();if(!/^[A-Za-z0-9_-]{10,}$/.test(limpo))return send(res,400,{erro:'esse id não parece um id de pasta do Drive'});await salvarPasta(nome,limpo);return send(res,200,{ok:true,ligado:true,marca:nome,raiz:limpo,pasta:limpo})}
  if(req.method!=='GET')return send(res,405,{erro:'método não permitido'});
  const q=Object.fromEntries(new URL(req.url,'http://x').searchParams),nome=q.marca||'Botanika',m=await marca(nome);
  if(q.diagnostico==='1')return send(res,200,{marca:m.marca,conta_servico_configurada:!!conta(),pasta_configurada:!!m.drive_pasta});
  if(!m.drive_pasta)return send(res,200,{ligado:false,marca:m.marca,erro:`A ${m.marca} ainda não tem pasta do Drive ligada.`});
  if(!conta())return send(res,200,{ligado:false,semChave:true,marca:m.marca,erro:'A AllianceOS ainda não tem a chave da conta de serviço do Google.'});
  const raiz=m.drive_pasta,pasta=q.pasta&&q.pasta!==raiz?q.pasta:raiz;if(pasta!==raiz&&!(await dentroDe(pasta,raiz)))return send(res,403,{erro:'essa pasta não é desta marca'});
  const busca=String(q.q||'').trim().slice(0,80),filtro=busca?`name contains '${aspas(busca)}' and trashed = false`:`'${aspas(pasta)}' in parents and trashed = false`;
  const lista=await drive('files',{q:filtro,fields:`nextPageToken, files(${CAMPOS})`,orderBy:'folder,name_natural',pageSize:'100',includeItemsFromAllDrives:'true',corpora:'allDrives',pageToken:q.pagina||null});
  const trilha=[];if(pasta!==raiz){let atual=pasta;for(let i=0;i<18;i++){const f=await drive(`files/${encodeURIComponent(atual)}`,{fields:'id,name,parents'});trilha.unshift({id:f.id,nome:f.name});if(f.id===raiz||!(f.parents||[]).length||(f.parents||[]).includes(raiz))break;atual=f.parents[0]}}
  const arquivos=(lista.files||[]).map(f=>({id:f.id,nome:f.name,tipo:f.mimeType,pasta:f.mimeType===PASTA,link:f.webViewLink||`https://drive.google.com/file/d/${f.id}/view`,icone:f.iconLink||'',miniatura:f.thumbnailLink||'',em:f.modifiedTime||'',tamanho:f.size?+f.size:null,dono:f.owners?.[0]?.displayName||''}));
  return send(res,200,{ligado:true,marca:m.marca,raiz,pasta,trilha,arquivos,proxima:lista.nextPageToken||null,busca:busca||null})
}catch(e){if(e?.status===401||e?.status===403)return authError(res,e);if(e.faltaChave)return send(res,200,{ligado:false,semChave:true,erro:'A AllianceOS ainda não tem a chave da conta de serviço do Google.'});console.error('[drive]',e);const msg=String(e.message||e).slice(0,300);if(/File not found|notFound|insufficient|permission/i.test(msg))return send(res,e.status===403?403:200,{ligado:false,semAcesso:true,erro:'O Drive não encontra ou não permite gravar nesta pasta. Confira o acesso da conta de serviço.'});return send(res,e.status||502,{erro:msg})}}
